name: mensapluskit
description: A small dart library to access the latest menus of all student canteens in Dresden.
version: 0.1.0
homepage: https://github.com/xiaoyuin/MensaPlusKit-dart
author: Xiaoyu Yin <yinxiaoyu39999@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  path: ^1.5.1
  http: "^0.11.3+16"
  intl: "^0.15.2"
  uuid: "^0.5.3"
  html: any


dev_dependencies:
  test: ^0.12.0
